import type { ProjectRecord } from '../model/types'
import { toProjectRecord } from './mappers'

export const projectFixtures: ProjectRecord[] = [
  toProjectRecord({
    id: 'bsky-feed-03',
    channel: '03',
    title: 'bsky.feed',
    year: 2026,
    status: 'in-progress',
    description: 'at-proto feed client with custom handle auth and a readable timeline. late-night weekend build.',
    tags: ['typescript', 'at-proto', 'react'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'pink', kind: 'bars' },
  }),
  toProjectRecord({
    id: 'crt-shader-kit',
    channel: '07',
    title: 'crt.shader',
    year: 2025,
    status: 'live',
    description: 'a tiny webgl shader kit: scanlines, mask, bloom, chromatic aberration. drop-in on any canvas.',
    tags: ['webgl', 'glsl', 'typescript'],
    links: { github: '#', site: '#' },
    thumbnail: { hue: 'cyan', kind: 'grid' },
  }),
  toProjectRecord({
    id: 'portra-log',
    channel: '12',
    title: 'portra.log',
    year: 2024,
    status: 'live',
    description: 'a film photo journal: scan, dust, stamp, publish. every entry dated by roll, not by week.',
    tags: ['next.js', 'sqlite', 'photography'],
    links: { github: null, site: '#' },
    thumbnail: { hue: 'amber', kind: 'noise' },
  }),
  toProjectRecord({
    id: 'tape-deck',
    channel: '15',
    title: 'tape.deck',
    year: 2024,
    status: 'archived',
    description: 'offline-first music library with cassette-style metadata. ran for a year. rotation.',
    tags: ['rust', 'tauri', 'sqlite'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'pink', kind: 'sig' },
  }),
  toProjectRecord({
    id: 'handle-dns',
    channel: '18',
    title: 'handle.dns',
    year: 2023,
    status: 'live',
    description: 'at-proto handle verifier over dns-txt. about sixty lines of go, deploys as one binary.',
    tags: ['go', 'dns', 'at-proto'],
    links: { github: '#', site: '#' },
    thumbnail: { hue: 'cyan', kind: 'grid' },
  }),
  toProjectRecord({
    id: 'dithermill',
    channel: '22',
    title: 'dithermill',
    year: 2023,
    status: 'live',
    description: 'browser-side image dithering: bayer, floyd-steinberg, atkinson. exports png with a palette lock.',
    tags: ['typescript', 'canvas', 'image'],
    links: { github: '#', site: '#' },
    thumbnail: { hue: 'cyan', kind: 'noise' },
  }),
  toProjectRecord({
    id: 'chyron-sh',
    channel: '26',
    title: 'chyron.sh',
    year: 2022,
    status: 'archived',
    description: 'cli that turns git commit streams into broadcast-chyron gif loops for socials. a joke that shipped.',
    tags: ['bash', 'ffmpeg', 'cli'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'amber', kind: 'bars' },
  }),
  toProjectRecord({
    id: 'sunset-parser',
    channel: '31',
    title: 'sunset.parser',
    year: 2022,
    status: 'archived',
    description: 'pure-js css gradient parser written to learn recursive descent. deprecated; do not use it.',
    tags: ['javascript', 'parser'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'amber', kind: 'sig' },
  }),
  toProjectRecord({
    id: 'latenite-bot',
    channel: '34',
    title: 'latenite.bot',
    year: 2021,
    status: 'archived',
    description: 'discord bot that ran a community listening-party. retired when the server closed.',
    tags: ['python', 'discord'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'pink', kind: 'noise' },
  }),
  toProjectRecord({
    id: 'v-dev',
    channel: '99',
    title: 'vinicius.dev',
    year: 2026,
    status: 'in-progress',
    description: 'this site. no tracking, no newsletter, lots of neon tape hiss. ch.99 is where the pirate broadcasts live.',
    tags: ['react', 'bun', 'typescript'],
    links: { github: '#', site: '#' },
    thumbnail: { hue: 'cyan', kind: 'bars' },
  }),
  toProjectRecord({
    id: 'pixel-glyph',
    channel: '42',
    title: 'pixel.glyph',
    year: 2025,
    status: 'live',
    description: 'a 5x7 bitmap font packaged as a webfont, with a tiny kerning table. used across this site.',
    tags: ['fonts', 'typescript', 'type-design'],
    links: { github: '#', site: '#' },
    thumbnail: { hue: 'pink', kind: 'grid' },
  }),
  toProjectRecord({
    id: 'feed-heartbeat',
    channel: '51',
    title: 'feed.heartbeat',
    year: 2024,
    status: 'archived',
    description: 'uptime monitor that posts a single heartbeat per minute. died when the vps did, fittingly.',
    tags: ['go', 'ops'],
    links: { github: '#', site: null },
    thumbnail: { hue: 'cyan', kind: 'sig' },
  }),
]

export function allProjectTags(projects: ProjectRecord[]) {
  return Array.from(new Set(projects.flatMap((project) => project.tags))).sort()
}
